### ISSUE TITLE
some questions about input and output

### ISSUE THREAD

**Issue by Danee-wawawa** [LuigiSigillo/StawGAN#1]
Hi, thank you for your work. In the paper. 
In the article, you introduced input and output, but I still don't understand. Can you provide more specific descriptions of the three parameters with red circles in the figure below? Thank you very much and we look forward to your reply.
![1684486801986](https://github.com/LuigiSigillo/StawGAN/assets/24379250/945d87a5-8cbe-4633-9bc4-f28bfa636487)

**Comment by LuigiSigillo** [comment]
Hi, thank you for the interesting question. Those are the definition given also in the paper:

- r_s is the image x_s segmented with just the targets (e.g. cars, buses etc.)
- t is the target modality expressed in a one-hot vector fashion, so the modality we want to translate the image in
- while r_t is the translated target image, so the segmented image in the translated in the target domain
I Hope it is more clear now :)
